import React, { useState } from 'react';
import { currentElection, historicalElections } from '../../data/mockData';
import { Download, FileText, BarChart3, PieChart, Calendar, Filter, Printer } from 'lucide-react';
import { motion } from 'framer-motion';
import BackButton from '../Common/BackButton';

const Reports: React.FC = () => {
  const [selectedReport, setSelectedReport] = useState('current-results');
  const [dateRange, setDateRange] = useState('current');
  const [format, setFormat] = useState('pdf');
  const [generating, setGenerating] = useState(false);

  const reportTypes = [
    {
      id: 'current-results',
      name: 'Current Election Results',
      description: 'Complete results of the ongoing election',
      icon: BarChart3,
      color: 'blue'
    },
    {
      id: 'voter-turnout',
      name: 'Voter Turnout Analysis',
      description: 'Detailed turnout statistics and demographics',
      icon: PieChart,
      color: 'green'
    },
    {
      id: 'historical-comparison',
      name: 'Historical Comparison',
      description: 'Compare results with previous elections',
      icon: Calendar,
      color: 'purple'
    },
    {
      id: 'constituency-wise',
      name: 'Constituency-wise Report',
      description: 'Detailed breakdown by constituency',
      icon: FileText,
      color: 'orange'
    }
  ];

  const handleGenerateReport = async () => {
    setGenerating(true);
    
    // Simulate report generation
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    // Create a mock PDF download
    const element = document.createElement('a');
    const file = new Blob([generateReportContent()], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `election-report-${selectedReport}-${Date.now()}.${format}`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    
    setGenerating(false);
  };

  const generateReportContent = () => {
    const report = reportTypes.find(r => r.id === selectedReport);
    const date = new Date().toLocaleDateString();
    
    return `
ELECTION COMMISSION OF INDIA
${report?.name.toUpperCase()}
Generated on: ${date}

===========================================

ELECTION DETAILS:
- Election: ${currentElection.title}
- Status: ${currentElection.status}
- Period: ${currentElection.startDate} to ${currentElection.endDate}

CANDIDATE RESULTS:
${currentElection.candidates.map((candidate, index) => `
${index + 1}. ${candidate.name} (${candidate.party})
   Votes: ${candidate.votes.toLocaleString()}
   Symbol: ${candidate.symbol}
`).join('')}

SUMMARY STATISTICS:
- Total Votes Cast: ${currentElection.candidates.reduce((sum, c) => sum + c.votes, 0).toLocaleString()}
- Number of Candidates: ${currentElection.candidates.length}
- Leading Candidate: ${currentElection.candidates.sort((a, b) => b.votes - a.votes)[0].name}

HISTORICAL CONTEXT:
${historicalElections.map(election => `
- ${election.year}: ${election.title}
  Winner: ${election.winner}
  Turnout: ${election.turnout}%
`).join('')}

===========================================
This report is generated by the Election Commission Portal
For official use only - Confidential
`;
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 to-green-50 py-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-8">
          <BackButton to="/" className="mb-4" />
          <h1 className="text-3xl font-bold text-blue-900 mb-4">Election Reports</h1>
          <p className="text-gray-600">
            Generate comprehensive reports for election analysis and documentation
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Report Selection */}
          <div className="lg:col-span-2">
            <div className="bg-white rounded-lg shadow-lg p-6 mb-6">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">Select Report Type</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {reportTypes.map((report, index) => {
                  const IconComponent = report.icon;
                  return (
                    <motion.div
                      key={report.id}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: index * 0.1 }}
                      className={`p-4 rounded-lg border-2 cursor-pointer transition-all ${
                        selectedReport === report.id
                          ? 'border-blue-500 bg-blue-50'
                          : 'border-gray-200 hover:border-gray-300'
                      }`}
                      onClick={() => setSelectedReport(report.id)}
                    >
                      <div className="flex items-start space-x-3">
                        <div className={`p-2 rounded-md bg-${report.color}-100`}>
                          <IconComponent className={`h-5 w-5 text-${report.color}-600`} />
                        </div>
                        <div>
                          <h3 className="font-medium text-gray-900">{report.name}</h3>
                          <p className="text-sm text-gray-600 mt-1">{report.description}</p>
                        </div>
                      </div>
                    </motion.div>
                  );
                })}
              </div>
            </div>

            {/* Report Preview */}
            <div className="bg-white rounded-lg shadow-lg p-6">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">Report Preview</h2>
              <div className="bg-gray-50 p-6 rounded-lg min-h-96">
                {selectedReport === 'current-results' && (
                  <div>
                    <h3 className="text-lg font-semibold mb-4">Current Election Results Summary</h3>
                    <div className="space-y-4">
                      <div className="grid grid-cols-2 gap-4">
                        <div className="bg-white p-4 rounded-lg">
                          <p className="text-sm text-gray-600">Total Candidates</p>
                          <p className="text-2xl font-bold text-blue-600">{currentElection.candidates.length}</p>
                        </div>
                        <div className="bg-white p-4 rounded-lg">
                          <p className="text-sm text-gray-600">Total Votes</p>
                          <p className="text-2xl font-bold text-green-600">
                            {currentElection.candidates.reduce((sum, c) => sum + c.votes, 0).toLocaleString()}
                          </p>
                        </div>
                      </div>
                      <div className="bg-white p-4 rounded-lg">
                        <h4 className="font-semibold mb-2">Leading Candidates</h4>
                        {currentElection.candidates
                          .sort((a, b) => b.votes - a.votes)
                          .slice(0, 3)
                          .map((candidate, index) => (
                            <div key={candidate.id} className="flex justify-between items-center py-2">
                              <span>{index + 1}. {candidate.name} ({candidate.party})</span>
                              <span className="font-medium">{candidate.votes.toLocaleString()} votes</span>
                            </div>
                          ))}
                      </div>
                    </div>
                  </div>
                )}

                {selectedReport === 'voter-turnout' && (
                  <div>
                    <h3 className="text-lg font-semibold mb-4">Voter Turnout Analysis</h3>
                    <div className="space-y-4">
                      <div className="bg-white p-4 rounded-lg">
                        <p className="text-sm text-gray-600">Current Turnout</p>
                        <p className="text-2xl font-bold text-blue-600">72.5%</p>
                      </div>
                      <div className="bg-white p-4 rounded-lg">
                        <h4 className="font-semibold mb-2">Turnout by Demographics</h4>
                        <div className="space-y-2">
                          <div className="flex justify-between">
                            <span>Age 18-25:</span>
                            <span>68.2%</span>
                          </div>
                          <div className="flex justify-between">
                            <span>Age 26-35:</span>
                            <span>74.8%</span>
                          </div>
                          <div className="flex justify-between">
                            <span>Age 36-45:</span>
                            <span>76.3%</span>
                          </div>
                          <div className="flex justify-between">
                            <span>Age 45+:</span>
                            <span>71.1%</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                )}

                {selectedReport === 'historical-comparison' && (
                  <div>
                    <h3 className="text-lg font-semibold mb-4">Historical Comparison</h3>
                    <div className="space-y-4">
                      {historicalElections.map(election => (
                        <div key={election.id} className="bg-white p-4 rounded-lg">
                          <div className="flex justify-between items-center">
                            <div>
                              <h4 className="font-semibold">{election.title}</h4>
                              <p className="text-sm text-gray-600">Winner: {election.winner}</p>
                            </div>
                            <div className="text-right">
                              <p className="font-semibold">{election.turnout}%</p>
                              <p className="text-sm text-gray-600">Turnout</p>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {selectedReport === 'constituency-wise' && (
                  <div>
                    <h3 className="text-lg font-semibold mb-4">Constituency-wise Breakdown</h3>
                    <div className="space-y-4">
                      {[
                        { name: 'Central Delhi', turnout: 74.6, leading: 'BJP', margin: 8.2 },
                        { name: 'South Delhi', turnout: 71.5, leading: 'AAP', margin: 5.7 },
                        { name: 'North Delhi', turnout: 73.0, leading: 'Congress', margin: 12.3 }
                      ].map(constituency => (
                        <div key={constituency.name} className="bg-white p-4 rounded-lg">
                          <div className="flex justify-between items-center">
                            <div>
                              <h4 className="font-semibold">{constituency.name}</h4>
                              <p className="text-sm text-gray-600">Leading: {constituency.leading}</p>
                            </div>
                            <div className="text-right">
                              <p className="font-semibold">{constituency.turnout}%</p>
                              <p className="text-sm text-gray-600">Turnout</p>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Generation Options */}
          <div className="space-y-6">
            <div className="bg-white rounded-lg shadow-lg p-6">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">Report Options</h2>
              
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Date Range
                  </label>
                  <select
                    value={dateRange}
                    onChange={(e) => setDateRange(e.target.value)}
                    className="w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="current">Current Election</option>
                    <option value="last7days">Last 7 Days</option>
                    <option value="last30days">Last 30 Days</option>
                    <option value="all">All Time</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Format
                  </label>
                  <select
                    value={format}
                    onChange={(e) => setFormat(e.target.value)}
                    className="w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="pdf">PDF Document</option>
                    <option value="xlsx">Excel Spreadsheet</option>
                    <option value="csv">CSV File</option>
                    <option value="txt">Text File</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Include Options
                  </label>
                  <div className="space-y-2">
                    <label className="flex items-center">
                      <input type="checkbox" className="rounded" defaultChecked />
                      <span className="ml-2 text-sm text-gray-700">Charts and Graphs</span>
                    </label>
                    <label className="flex items-center">
                      <input type="checkbox" className="rounded" defaultChecked />
                      <span className="ml-2 text-sm text-gray-700">Summary Statistics</span>
                    </label>
                    <label className="flex items-center">
                      <input type="checkbox" className="rounded" />
                      <span className="ml-2 text-sm text-gray-700">Raw Data</span>
                    </label>
                    <label className="flex items-center">
                      <input type="checkbox" className="rounded" defaultChecked />
                      <span className="ml-2 text-sm text-gray-700">Candidate Photos</span>
                    </label>
                  </div>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-lg shadow-lg p-6">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">Generate Report</h2>
              
              <button
                onClick={handleGenerateReport}
                disabled={generating}
                className="w-full bg-blue-900 text-white py-3 px-4 rounded-md hover:bg-blue-800 disabled:opacity-50 disabled:cursor-not-allowed transition-colors mb-4"
              >
                {generating ? (
                  <div className="flex items-center justify-center space-x-2">
                    <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                    <span>Generating...</span>
                  </div>
                ) : (
                  <div className="flex items-center justify-center space-x-2">
                    <Download className="h-4 w-4" />
                    <span>Generate & Download</span>
                  </div>
                )}
              </button>

              <button className="w-full bg-gray-600 text-white py-2 px-4 rounded-md hover:bg-gray-700 transition-colors">
                <div className="flex items-center justify-center space-x-2">
                  <Printer className="h-4 w-4" />
                  <span>Print Preview</span>
                </div>
              </button>
            </div>

            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
              <h3 className="font-semibold text-yellow-800 mb-2">Report Guidelines</h3>
              <ul className="text-sm text-yellow-700 space-y-1">
                <li>• Reports contain sensitive election data</li>
                <li>• For official use only</li>
                <li>• Maintain confidentiality</li>
                <li>• Regular backups recommended</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Reports;